---
- hosts: mac 
  vars:
    k8s_version: "v1.9.2"
    etcd_version: "v3.2.15"
    cfssl_version: "R1.2"
    traefik_version: "v1.3.8"
    crio_version: "v1.9.0"
    base_dir: "/Users/dan/Work/k8s_vagrant_ansible"
  tasks:
#    - include: tasks/download_tools.yml
#    - include: tasks/cert.yml
    - include: tasks/generate-kubeconfig-kube-proxy.yml


#- hosts: all
#  sudo: true
#  vars:
#    k8s_versionx: "v1.9.2"
#    etcd_version: "v3.2.15"
#    cfssl_version: "R1.2"
#    traefik_version: "v1.3.8"
#    crio_version: "v1.9.0"
#    dir: "/Users/dys/Desktop/k8s/kubernetes-the-hard-way-vagrant" 
#  tasks:
##    - include: tasks/download_tools.yml
#    - include: tasks/task3.yml
