---
- name: change ca cert
  command: bash -lc "cd {{ base_dir }}/certificates && export PATH=$HOME/go/bin:$PATH  && cfssl gencert -initca ca-csr.json | cfssljson -bare ca" 

- name: generate admin cert
  command: bash -lc "cd {{ base_dir }}/certificates && export PATH=$HOME/go/bin:$PATH && cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json  -profile=kubernetes admin-csr.json | cfssljson -bare admin"


 

- name: generate worker cert
  command: bash -lc "cd {{ base_dir }}/certificates && export PATH=$HOME/go/bin:$PATH && cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -hostname=worker-{{ item }},192.168.199.2{{ item }} -profile=kubernetes worker-{{ item }}-csr.json | cfssljson -bare worker-{{ item }}"
  loop:
    - 0
    - 1
    - 2

- name: generate kube-proxy cert
  command: bash -lc "cd {{ base_dir }}/certificates && export PATH=$HOME/go/bin:$PATH && cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json  -profile=kubernetes kube-proxy-csr.json | cfssljson -bare kube-proxy"

 
- name: generate kubernetes cert
  command: bash -lc "cd {{ base_dir }}/certificates && export PATH=$HOME/go/bin:$PATH && cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json  -hostname=10.32.0.1,192.168.199.40,192.168.199.10,192.168.199.11,192.168.199.12,127.0.0.1,kubernetes.default -profile=kubernetes kubernetes-csr.json | cfssljson -bare kubernetes"


