---
- name: download kube tools locally
  shell: curl -sSL -O "https://storage.googleapis.com/kubernetes-release/release/{{ k8s_version}}/bin/linux/amd64/{{ item }}"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-schedule
    - kube-proxy
    - kubelet
      # - kubectl

- name: download etcd_version locally
  shell: curl -sSL -O "https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"

- name: Extract etcd into tools
  unarchive:
    src: "etcd-{{ etcd_version }}-linux-amd64.tar.gz" 
    dest: "{{ base_dir }}/tools/"

- name: download cni=pligins tools locally
  shell: curl -sSL -O "https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz" 

- name: download runc tools locally
  shell: curl -sSL -O "https://github.com/opencontainers/runc/releases/download/v1.0.0-rc4/runc.amd64" 

- name: download crio tools locally
  shell: curl -sSL -O "https://files.schu.io/pub/cri-o/crio-amd64-{{ crio_version }}.tar.gz"
 

- name: Extract etcd into tools
  unarchive:
    src: "crio-amd64-{{ crio_version }}.tar.gz"
    dest: "{{ base_dir }}/tools/"

- name: rename runc.amd64 file 
  command: mv runc.amd64 runc 

- name: download traefik tools locally
  shell: curl -sSL -O "https://github.com/containous/traefik/releases/download/{{ traefik_version }}/traefik_linux-amd64"

- name: rename traefik_linux-amd64 file
  command: mv traefik_linux-amd64 traefik

- name: Set proper permission on k8s tools
  file: path="{{ base_dir }}/{{ item }}" mode=0775 
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-schedule
    - kube-proxy
    - kubelet
    - kubectl
