---
- name: set-cluster kubernetes-the-hard-way
  command: kubectl config set-cluster kubernetes-the-hard-way --certificate-authority="{{ base_dir }}/certificates/ca.pem" --embed-certs=true --server=https://192.168.199.40:6443 --kubeconfig="{{ base_dir }}/config/{{ item }}.kubeconfig"
  with_items:
    - worker-0
    - worker-1
    - worker-2
 


- name: set-credentials kube-proxy
  command: kubectl config set-credentials system:node:{{ item }} --client-certificate="{{ base_dir }}/certificates/{{ item }}.pem" --client-key="{{ base_dir }}/certificates/{{ item }}-key.pem" --embed-certs=true --kubeconfig="{{ base_dir }}/config/{{ item }}.kubeconfig"
  with_items:
    - worker-0
    - worker-1
    - worker-2 

- name: set-context default
  command: kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:node:{{ item }} --kubeconfig="{{ base_dir }}/config/{{ item }}.kubeconfig"
  with_items: 
    - worker-0
    - worker-1
    - worker-2

- name: use-context default
  command: kubectl config use-context default --kubeconfig="{{ base_dir }}/config/{{ item }}.kubeconfig"
  with_items:
    - worker-0
    - worker-1
    - worker-2
