---
- name: set-cluster kubernetes-the-hard-way
  command: kubectl config set-cluster kubernetes-the-hard-way --certificate-authority="{{ base_dir }}/certificates/ca.pem" --embed-certs=true --server=https://192.168.199.10:6443 --kubeconfig="{{ base_dir }}/config/kube-proxy.kubeconfig"


- name: set-credentials kube-proxy
  command: kubectl config set-credentials kube-proxy --client-certificate="{{ base_dir }}/certificates/kube-proxy.pem" --client-key="{{ base_dir }}/certificates/kube-proxy-key.pem" --embed-certs=true --kubeconfig="{{ base_dir }}/config/kube-proxy.kubeconfig"


- name: set-context default
  command: kubectl config set-context default --cluster=kubernetes-the-hard-way --user=kube-proxy --kubeconfig="{{ base_dir }}/config/kube-proxy.kubeconfig"
 
- name: use-context default
  command: kubectl config use-context default --kubeconfig="{{ base_dir }}/config/kube-proxy.kubeconfig"

