---
- name: copy etc files to controllers 
  copy: 
    src: /Users/dan/Work/k8s_vagrant_ansible/tools/etcd-{{ etcd_version }}-linux-amd64/etcd
    dest: /usr/local/bin
    mode: 0755

- name: create etc/etcd files on controllers
  file: 
    path=/etc/etcd
    state=directory
 
- name: create /var/lib/etcd files on controllers
  file:
    path=/var/lib/etcd
    state=directory

- name: copy cert to controllers servers 
  copy:
    src: /Users/dan/Work/k8s_vagrant_ansible/certificates/{{ item }}
    dest: /etc/etcd/{{ item }} 
  with_items: 
    - ca.pem
    - kubernetes-key.pem
    - kubernetes.pem

#- name: copy systemd to controllers servers
#  copy:
#    src: /Users/dan/Work/k8s_vagrant_ansible/config/{{ item }}-etcd.service
#    dest: /etc/systemd/system/etcd.service
#  with_items: "{{ groups['controllers'] }}"

- name: copy systemd to controllers servers
  copy:
    src: /Users/dan/Work/k8s_vagrant_ansible/config/{{ inventory_hostname }}-etcd.service
    dest: /etc/systemd/system/etcd.service

- name: just force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes

- name: enable etc systemd
  systemd:
    name: etcd
    state: started
    enabled: True
